### PR TITLE
restyle userspace macro using duplicate crate

### PR DESCRIPTION
**Pull request by uccidibuti**
i've restyled userspace macros using duplicate crate, i think that this makes macros more readable..

### CODE REVIEW

**Comment by laarmen** [comment]
I like it, but sadly the new dependency doesn't compile on 1.34. I'm working on a patchset to fix that for them, do you mind if we hold off on this PR until the situation with `duplicate` MSRV is clarified ?

**Comment by uccidibuti** [comment]
Don't worry Simon, it's my fault that i didn't try to build with Rust 1.34.2 before compile..  so for now we can also leave this PR in pending to find a solution..

**Comment by laarmen** [comment]
It allright, that's why we have CI in place :-).

One of the PRs has already landed (for a test dependency of `duplicate`).

**Comment by Emoun** [comment]
I have published [`duplicate` v0.2.8](https://crates.io/crates/duplicate/0.2.8), which should work on rust 1.34.
Note that the new release doesn't document `duplicate`'s new MSRV policy (I will publish a new release later with this), though you can find it in [Emoun/duplicate#18](https://github.com/Emoun/duplicate/issues/18#issuecomment-697554595) for now.
Also, as per the new policy, the MSRV is 1.34 as long as you __do not__ use the default features, as the `module_disambiguation` feature bumps the MSRV to 1.42. Therefore, I'd recommend you use `duplicate = {version = "0.2.8", default-features=false}`

**Comment by uccidibuti** [comment]
> I have published [`duplicate` v0.2.8](https://crates.io/crates/duplicate/0.2.8), which should work on rust 1.34.
> Note that the new release doesn't document `duplicate`'s new MSRV policy (I will publish a new release later with this), though you can find it in [Emoun/duplicate#18](https://github.com/Emoun/duplicate/issues/18#issuecomment-697554595) for now.
> Also, as per the new policy, the MSRV is 1.34 as long as you **do not** use the default features, as the `module_disambiguation` feature bumps the MSRV to 1.42. Therefore, I'd recommend you use `duplicate = {version = "0.2.8", default-features=false}`

Thank you for adding Rust 1.34.2 support =)!

**Comment by uccidibuti** [comment]
Hei @laarmen, now can we merge this PR =)?

**Pull request merged**
